[package]
name = "panda-server"
version = "0.1.0"
authors = ["Ibiyemi Abiodun <ibiyemi@intulon.com>"]
edition = "2018"

[dependencies]
warp = "0.2.2"
tokio = { version = "0.2.13", features = ["full"] }
log = "0.4"
pretty_env_logger = "0.4"